version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge
